name: 'Terraform FMT, Validate & Plan'
 
on:
  pull_request:
    branches: [ master ]

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform FMT, Validate & Plan'
    runs-on: ubuntu-latest
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: ./azure-resource-group

    steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v2

        # Install the preferred version of Terraform CLI 
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.0.10

        - name: Terraform Init
          id: init
          env:   
            ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
            RM_CLIENT_SECRET: ${{s ecrets.TF_ARM_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: <${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: <${{ secrets.TF_ARM_TENANT_ID }}
            RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
            STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
            CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
          run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"

        - name: Terraform format
          id: fmt
          run: terraform fmt -check

        - name: Terraform validate
          id: validate
          if: (success() || failure())
          run: terraform validate -no-color

#        - name: Terraform plan
#          id: plan
#          run: terraform plan