name: 'Terraform FMT & Validate'
 
on:
  push:
    branches-ignore:
      - master

env:
  TF_LOG: INFO
  ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: <${{secrets.TF_ARM_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: <${{secrets.TF_ARM_TENANT_ID}}

jobs:
  terraform:
    name: 'Terraform FMT & Validate'
    runs-on: ubuntu-latest
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: ./azure-resource-group

    steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v2

        # Install the preferred version of Terraform CLI 
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.0.10

        - name: Terraform Init
          id: init
          run: terraform init

        - name: Terraform format
          id: fmt
          run: terraform fmt -check

        - name: Terraform validate
          id: validate
          if: (success() || failure())
          run: terraform validate -no-color

        - name: Terraform plan
          id: plan
          run: terraform plan