name: 'Terraform FMT & Validate'
 
on:
  push:
    branches-ignore:
      - master

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform FMT & Validate'
    runs-on: ubuntu-latest
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: ./azure-resource-group

    steps:
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Creating Azure Function App'
        uses: azure/CLI@v1
      
      - name: 'Azure account show'
        run: az account show

        # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

        # Install the preferred version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.10
#          
#           # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
#        - name: Terraform Init
#          id: init
#          env:
#            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
#            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
#            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
#            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
#            RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
#            STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
#            CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
#          run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"    
#
#        - name: Terraform format
#          id: fmt
#          run: terraform fmt -check
#
#        - name: Terraform validate
#          id: validate
#          if: (success() || failure())
#          run: terraform validate -no-color